#!/bin/bash

VIM_COMMAND=vim
VIM_CONFIG=vimrc
VIM_PLUGIN_FILE=$HOME/.vim/autoload/plug.vim
VIM_PLUGIN_DIR=$HOME/.vim/bundle
VIM_COLORS_DIR=$HOME/.vim/colors
VIM_RC_DIRECTORY=$HOME/.vim

if [ "$VIM_COMMAND" = "nvim" ]; then
  VIM_CONFIG=init.vim
  VIM_RC_DIRECTORY=$HOME/.config/nvim
  VIM_PLUGIN_FILE=$HOME/.config/nvim/autoload/plug.vim
  VIM_PLUGIN_DIRECTORY=$HOME/.config/nvim/plugged
  VIM_COLORS_DIRECTORY=$HOME/.config/nvim/local-plugins/color-schemes/colors
fi

function wrap_execute {
  echo "$@"
  "$@"
}

function make_backup {
  # If file exists
  if [ -a $1 ] && [ -d $1.bak ]; then
    echo "ERROR: Cannot backup $1 to $1.bak as latter exists as directory"
  elif [ -a $1 ]; then
    echo "Backing up $1 to $1.bak"
    mv $1 $1.bak
  fi
}

function create_directory {
  if [ ! -d $1 ] ; then
    wrap_execute mkdir $1
  fi
}

function backup_and_symlink {
  source_filepath=$1
  destination_filepath=$2
  # If file exists and is not a symlink
  [ -a $destination_filepath ] && [ ! -h $destination_filepath ] && make_backup $destination_filepath
  wrap_execute ln -fs $source_filepath $destination_filepath
}

function configure_vim {
  create_directory $VIM_RC_DIRECTORY
  backup_and_symlink $PWD/vim_configs/$VIM_CONFIG $VIM_RC_DIRECTORY/$VIM_CONFIG
  backup_and_symlink $PWD/vim_configs/python_mappings.vim $VIM_RC_DIRECTORY/python_mappings.vim

  VIM_COLOR_FILE=Tomorrow-Night.vim
  create_directory $VIM_COLORS_DIR
  backup_and_symlink $PWD/vim_configs/$VIM_COLOR_FILE $VIM_COLORS_DIR/$VIM_COLOR_FILE
}

function install_vim_plugins {
  make_backup $VIM_PLUGIN_FILE
  make_backup $VIM_PLUGIN_DIR
  wrap_execute curl -fLo $VIM_PLUGIN_FILE --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  VUNDLER_FOLDER=$HOME/.vim/bundle/Vundle.vim
  if [ -d $VUNDLER_FOLDER ]; then
    cd $VUNDLER_FOLDER
    wrap_execute git pull
    cd -
  else
    wrap_execute git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  fi

  wrap_execute $VIM_COMMAND +PluginInstall +qall
}


function symlink_root_files {
  for root_file in $(ls root_files/*); do
    backup_and_symlink $PWD/$root_file $(echo $HOME/$root_file | sed 's/root_files\//./')
  done
}

function configure_bin_folders {
  [ -f $HOME/.bin ] && [ ! -h $HOME/.bin ] && make_backup $HOME/.bin
  wrap_execute ln -fs $PWD/bin/ $HOME/.bin

  [ -d $HOME/.bin.local ] || wrap_execute mkdir $HOME/.bin.local
}

symlink_root_files
install_vim_plugins
configure_vim
configure_bin_folders

# Install how_do_i
touch ~/.how_do_i
